import type { Metadata } from "next";
import type { ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Car, Check, CheckCircle2, CircleAlert, Clock3, ExternalLink, Globe2, Instagram, Mail, MapPin, MessageCircle, Mountain, Navigation, Phone, TentTree, Users } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { CampgroundCard } from "@/components/campground-card";
import { CampgroundGallery } from "@/components/campground-gallery";
import { CampgroundDetailMap } from "@/components/campground-detail-map";
import { CampgroundTrustPanel } from "@/components/campground-trust-panel";
import { JsonLd, absoluteUrl, breadcrumbJsonLd } from "@/components/json-ld";
import { getCampgroundBySlug, getRelatedCampgrounds } from "@/lib/campgrounds/repository";
import { getCampgroundDirectoryFacets } from "@/lib/campgrounds/repository";
import type { CampgroundContactDetail } from "@/types/campground";

const rupiah = new Intl.NumberFormat("id-ID");
async function resolveCampgroundGeography(provinceName:string,regencyName:string){const facets=await getCampgroundDirectoryFacets();const province=facets.provinces.find(x=>x.label===provinceName);const regency=province?facets.regencies.find(x=>x.label===regencyName&&x.province===province.value):undefined;return{province,regency};}
const verificationLabel = { verified: "Terverifikasi ICL", community_updated: "Diperbarui komunitas", needs_update: "Perlu diperbarui" };
const verificationTone = { verified: "bg-[#eaf2ec] text-forest-800", community_updated: "bg-[#eef3e7] text-forest-800", needs_update: "bg-[#fff3dd] text-[#76531c]" };
const priceTypeLabel = { entrance: "Tiket masuk", camping: "Camping", parking: "Parkir", tent_rental: "Sewa tenda", equipment_rental: "Sewa perlengkapan", firewood: "Kayu bakar", other: "Lainnya" };
type Props = { params: Promise<{ slug: string }> };
export const dynamic = "force-dynamic";

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params; const campground = await getCampgroundBySlug(slug);
  if (!campground) return { title: "Campground tidak ditemukan" };
  return { title: campground.name, description: campground.shortDescription, openGraph: { title: campground.name, description: campground.shortDescription, images: [campground.image] } };
}

function contactHref(contact: CampgroundContactDetail): string | null {
  const raw = contact.value.trim(); if (!raw) return null;
  if (contact.type === "whatsapp") { const digits = raw.replace(/\D/g, "").replace(/^0/, "62"); return digits.length >= 8 ? `https://wa.me/${digits}` : null; }
  if (contact.type === "phone") { const phone = raw.replace(/[^\d+]/g, ""); return phone.length >= 6 ? `tel:${phone}` : null; }
  if (contact.type === "email") return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(raw) ? `mailto:${raw}` : null;
  if (contact.type === "instagram") { const handle = raw.replace(/^https?:\/\/(www\.)?instagram\.com\//i, "").replace(/^@/, "").split(/[/?#]/)[0]; return /^[A-Za-z0-9._]+$/.test(handle) ? `https://www.instagram.com/${handle}/` : null; }
  if (contact.type === "website") { try { const url = new URL(/^https?:\/\//i.test(raw) ? raw : `https://${raw}`); return url.protocol === "https:" || url.protocol === "http:" ? url.toString() : null; } catch { return null; } }
  return null;
}
function ContactIcon({ type }: { type: CampgroundContactDetail["type"] }) { if (type === "whatsapp") return <MessageCircle size={18}/>; if (type === "instagram") return <Instagram size={18}/>; if (type === "website") return <Globe2 size={18}/>; if (type === "email") return <Mail size={18}/>; return <Phone size={18}/>; }

export default async function CampgroundDetailPage({ params }: Props) {
  const { slug } = await params; const campground = await getCampgroundBySlug(slug); if (!campground) notFound();
  const related = await getRelatedCampgrounds(campground, 3);
  const hasVerificationDate = campground.lastVerifiedAt !== "1970-01-01";
  const verifiedDate = hasVerificationDate ? new Intl.DateTimeFormat("id-ID", { day: "numeric", month: "long", year: "numeric" }).format(new Date(`${campground.lastVerifiedAt}T00:00:00`)) : "Belum diverifikasi";
  const mapsUrl = `https://www.google.com/maps/search/?api=1&query=${campground.latitude},${campground.longitude}`;
  const locationLine = [campground.district, campground.regency, campground.province].filter(Boolean).join(", ");
  const geography = await resolveCampgroundGeography(campground.province, campground.regency);
  const contacts = campground.contacts.map(contact => ({ contact, href: contactHref(contact) })).filter((x): x is { contact: CampgroundContactDetail; href: string } => Boolean(x.href));
  const primaryContact = contacts.find(x => x.contact.isPrimary) ?? contacts.find(x => x.contact.type === "whatsapp") ?? contacts[0];
  const hasValidCoordinates = Number.isFinite(campground.latitude) && Number.isFinite(campground.longitude) && campground.latitude >= -90 && campground.latitude <= 90 && campground.longitude >= -180 && campground.longitude <= 180;

  const detailPath = `/camping/${campground.slug}`;
  const detailBreadcrumb = [{ name: "Camping", path: "/camping" }, ...(geography.province ? [{ name: geography.province.label, path: `/camping/${geography.province.value}` }] : []), ...(geography.province && geography.regency ? [{ name: geography.regency.label, path: `/camping/${geography.province.value}/${geography.regency.value}` }] : []), { name: campground.name, path: detailPath }];
  const placeJsonLd = { "@context": "https://schema.org", "@type": "Place", name: campground.name, url: absoluteUrl(detailPath), description: campground.shortDescription, image: campground.image, address: { "@type": "PostalAddress", streetAddress: campground.address, addressLocality: campground.regency || campground.district, addressRegion: campground.province, addressCountry: "ID" }, ...(hasValidCoordinates ? { geo: { "@type": "GeoCoordinates", latitude: campground.latitude, longitude: campground.longitude } } : {}) };

  return <main><JsonLd data={breadcrumbJsonLd(detailBreadcrumb)}/><JsonLd data={placeJsonLd}/><SiteHeader/><div className="container-icl py-7 md:py-10">
    <nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-sm font-semibold text-black/50"><Link href="/camping" className="icl-focus rounded hover:text-forest-800">Camping</Link>{geography.province&&<><span>/</span><Link href={`/camping/${geography.province.value}`} className="icl-focus rounded hover:text-forest-800">{geography.province.label}</Link></>}{geography.province&&geography.regency&&<><span>/</span><Link href={`/camping/${geography.province.value}/${geography.regency.value}`} className="icl-focus rounded hover:text-forest-800">{geography.regency.label}</Link></>}<span>/</span><span className="text-black/75">{campground.name}</span></nav>
    <section className="mt-6 overflow-hidden rounded-[28px] border border-black/5 bg-white shadow-sm md:rounded-[32px]">
      <div className="relative aspect-[16/10] bg-forest-100 sm:aspect-[16/8] lg:aspect-[2.15/1]"><Image src={campground.image} alt={campground.photos[0]?.altText || `Foto ${campground.name}`} fill priority className="object-cover" sizes="100vw"/><div className="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-black/70 via-black/20 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5 text-white sm:p-7 md:p-9 lg:p-10"><div className="flex flex-wrap gap-2"><span className={`flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-extrabold ${verificationTone[campground.verificationStatus]}`}><CheckCircle2 size={14}/>{verificationLabel[campground.verificationStatus]}</span>{campground.types.map(type => <span key={type} className="rounded-full border border-white/25 bg-black/25 px-3 py-1.5 text-xs font-bold backdrop-blur-sm">{type}</span>)}</div><h1 className="mt-4 max-w-4xl text-3xl font-extrabold tracking-[-0.035em] sm:text-4xl md:text-5xl lg:text-6xl">{campground.name}</h1><p className="mt-3 flex items-start gap-2 text-sm font-semibold text-white/90"><MapPin size={18}/>{locationLine || campground.address}</p></div></div>
      <div className="grid gap-6 p-5 sm:p-7 md:p-9 lg:grid-cols-[1fr_auto] lg:items-center lg:p-10"><div><p className="max-w-3xl text-base leading-7 text-black/65 md:text-lg">{campground.shortDescription}</p><p className="mt-3 flex gap-2 text-sm text-black/50"><MapPin size={16}/>{campground.address}</p></div><div className="flex flex-wrap gap-3">{campground.priceFrom > 0 && <div className="min-w-[170px] rounded-2xl bg-sand px-5 py-4"><p className="text-[11px] font-bold uppercase text-black/45">Harga mulai</p><p className="mt-1 text-xl font-extrabold text-forest-900">Rp{rupiah.format(campground.priceFrom)}</p><p className="text-xs text-black/45">per {campground.priceUnit}</p></div>}{primaryContact && <a href={primaryContact.href} target={primaryContact.contact.type === "phone" || primaryContact.contact.type === "email" ? undefined : "_blank"} rel="noreferrer" className="icl-button-primary icl-focus min-h-[58px] px-6 py-3 text-sm"><ContactIcon type={primaryContact.contact.type}/>Hubungi pengelola</a>}</div></div>
    </section>

    <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px] lg:items-start"><div>
      <section className="grid grid-cols-2 gap-3 md:grid-cols-4"><Fact icon={<Mountain size={20}/>} label="Elevasi" value={campground.elevationM ? `${campground.elevationM.toLocaleString("id-ID")} mdpl` : "—"}/><Fact icon={<Users size={20}/>} label="Kapasitas" value={campground.capacityPeople ? `${campground.capacityPeople.toLocaleString("id-ID")} orang` : "—"}/><Fact icon={<Car size={20}/>} label="Akses" value={campground.access[0] ?? "—"}/><Fact icon={<TentTree size={20}/>} label="Tipe" value={campground.types[0] ?? "Camping"}/></section>
      {campground.description && <Section eyebrow="Tentang tempat ini" title="Kenali campground sebelum berangkat"><p className="max-w-3xl whitespace-pre-line text-base leading-8 text-black/65">{campground.description}</p></Section>}
      <Section eyebrow="Fasilitas" title="Yang tersedia di lokasi">{campground.facilityDetails.length ? <div className="grid gap-3 sm:grid-cols-2">{campground.facilityDetails.map((item, i) => <div key={`${item.name}-${i}`} className="flex items-start gap-3 rounded-2xl border border-black/5 bg-white p-4"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-[#eaf2ec] text-forest-700"><Check size={15}/></span><div><p className="text-sm font-bold">{item.name}</p>{item.note && <p className="mt-1 text-xs leading-5 text-black/50">{item.note}</p>}</div></div>)}</div> : <Empty text="Informasi fasilitas belum tersedia."/>}</Section>
      <Section eyebrow="Akses & kecocokan" title="Menuju lokasi dan siapa yang cocok"><div className="grid gap-8 md:grid-cols-2"><div><h3 className="text-lg font-extrabold">Akses kendaraan</h3>{campground.accessDescription && <p className="mt-3 text-sm leading-6 text-black/55">{campground.accessDescription}</p>}<div className="mt-4 space-y-2">{campground.accessDetails.map((item, i) => <div key={`${item.vehicleType}-${i}`} className="rounded-2xl bg-sand px-4 py-3"><p className="text-sm font-bold">{item.vehicleType}</p>{item.note && <p className="mt-1 text-xs text-black/50">{item.note}</p>}</div>)}</div></div><div><h3 className="text-lg font-extrabold">Cocok untuk</h3><div className="mt-4 flex flex-wrap gap-2">{campground.suitableFor.map(item => <span key={item} className="rounded-full bg-sand px-3 py-2 text-sm font-semibold">{item}</span>)}</div></div></div></Section>
      {(campground.checkInInfo || campground.goodToKnow) && <Section eyebrow="Sebelum berangkat" title="Informasi penting untuk camper"><div className="grid gap-4 md:grid-cols-2">{campground.checkInInfo && <InfoPanel icon={<Clock3 size={20}/>} title="Check-in & kedatangan" text={campground.checkInInfo}/>} {campground.goodToKnow && <InfoPanel icon={<CircleAlert size={20}/>} title="Perlu diketahui" text={campground.goodToKnow}/>}</div></Section>}
      <Section eyebrow="Harga" title="Rincian biaya">{campground.prices.length ? <div className="overflow-hidden rounded-2xl border border-black/10 bg-white">{campground.prices.map((price, i) => <div key={price.id} className={`grid gap-2 p-5 sm:grid-cols-[1fr_auto] ${i ? "border-t border-black/10" : ""}`}><div><p className="text-xs font-bold uppercase text-black/40">{priceTypeLabel[price.type]}</p><p className="mt-1 font-extrabold">{price.label}</p>{price.note && <p className="mt-1 text-xs text-black/50">{price.note}</p>}</div><div className="sm:text-right"><p className="text-lg font-extrabold text-forest-900">Rp{rupiah.format(price.amountIdr)}</p>{price.unit && <p className="text-xs text-black/45">per {price.unit}</p>}</div></div>)}</div> : <Empty text="Rincian harga belum tersedia."/>}<p className="mt-3 text-xs text-black/45">Harga dapat berubah. Konfirmasi kembali kepada pengelola sebelum berangkat.</p></Section>
      <Section eyebrow="Kontak pengelola" title="Konfirmasi sebelum berangkat">{contacts.length ? <div className="grid gap-3 sm:grid-cols-2">{contacts.map(({ contact, href }) => <a key={contact.id} href={href} target={contact.type === "phone" || contact.type === "email" ? undefined : "_blank"} rel="noreferrer" className="icl-focus flex items-center gap-4 rounded-2xl border border-black/10 bg-white p-4"><span className="grid size-10 place-items-center rounded-full bg-[#eaf2ec] text-forest-700"><ContactIcon type={contact.type}/></span><span className="min-w-0 flex-1"><span className="block text-sm font-extrabold">{contact.label || contact.type}</span><span className="block truncate text-xs text-black/45">{contact.value}</span></span><ExternalLink size={15}/></a>)}</div> : <Empty text="Kontak publik pengelola belum tersedia."/>}</Section>
      {campground.photos.length > 0 && <Section eyebrow="Galeri" title={`Lihat suasana ${campground.name}`}><CampgroundGallery name={campground.name} photos={campground.photos}/></Section>}
      {hasValidCoordinates && <Section eyebrow="Lokasi" title="Temukan campground di peta"><div className="overflow-hidden rounded-[24px] border border-black/10 bg-white"><CampgroundDetailMap name={campground.name} latitude={campground.latitude} longitude={campground.longitude}/><div className="flex flex-col gap-4 border-t border-black/10 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-extrabold">{campground.name}</p><p className="mt-1 max-w-xl text-sm leading-6 text-black/55">{campground.address}</p></div><a href={mapsUrl} target="_blank" rel="noreferrer" className="icl-button-primary icl-focus shrink-0 px-5 py-3 text-sm"><Navigation size={17}/>Petunjuk arah</a></div></div></Section>}
      <CampgroundTrustPanel status={campground.verificationStatus} lastVerifiedAt={campground.lastVerifiedAt}/>
    </div>

    <aside className="icl-card p-6 lg:sticky lg:top-28">{campground.priceFrom > 0 && <><p className="text-xs font-bold uppercase text-black/40">Harga mulai</p><p className="mt-2 text-2xl font-extrabold text-forest-900">Rp{rupiah.format(campground.priceFrom)}</p><p className="text-xs text-black/45">per {campground.priceUnit}</p><div className="my-6 border-t border-black/10"/></>}<p className="text-xs font-bold uppercase text-black/40">Ringkasan lokasi</p><p className="mt-3 text-lg font-extrabold text-forest-900">{campground.regency || campground.province}</p><p className="mt-2 text-sm leading-6 text-black/55">{campground.address}</p>{primaryContact && <a href={primaryContact.href} target="_blank" rel="noreferrer" className="icl-button-primary icl-focus mt-5 w-full px-5 py-3 text-sm"><ContactIcon type={primaryContact.contact.type}/>Hubungi pengelola</a>}<a href={mapsUrl} target="_blank" rel="noreferrer" className="icl-button-secondary icl-focus mt-3 w-full px-5 py-3 text-sm"><Navigation size={17}/>Petunjuk arah</a><div className="my-6 border-t border-black/10"/><p className="text-sm font-bold">Status data</p><div className="mt-3 flex items-center gap-2 text-sm font-semibold text-forest-800"><CheckCircle2 size={17}/>{verificationLabel[campground.verificationStatus]}</div><p className="mt-2 text-xs leading-5 text-black/45">{hasVerificationDate ? `Terakhir diperiksa ${verifiedDate}.` : "Data ini belum memiliki tanggal verifikasi."}</p></aside>
    </div>

    {related.length > 0 && <section className="mt-20 border-t border-black/10 pt-12"><p className="icl-eyebrow">Lanjut menjelajah</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight">Campground terkait</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{related.map(item => <CampgroundCard key={item.id} campground={item}/>)}</div></section>}
  </div></main>;
}

function Fact({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-black/5 bg-white p-4"><span className="text-forest-700">{icon}</span><p className="mt-3 text-xs text-black/45">{label}</p><p className="mt-1 text-sm font-extrabold">{value}</p></div>; }
function Section({ eyebrow, title, children }: { eyebrow: string; title: string; children: ReactNode }) { return <section className="mt-12 border-t border-black/10 pt-10"><p className="icl-eyebrow">{eyebrow}</p><h2 className="mb-6 mt-2 text-2xl font-extrabold tracking-tight">{title}</h2>{children}</section>; }
function InfoPanel({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="rounded-2xl border border-black/5 bg-white p-5"><span className="text-forest-700">{icon}</span><h3 className="mt-3 font-extrabold">{title}</h3><p className="mt-2 whitespace-pre-line text-sm leading-6 text-black/55">{text}</p></div>; }
function Empty({ text }: { text: string }) { return <p className="text-sm text-black/50">{text}</p>; }
