import type { Campground, CampgroundDetail, VerificationStatus } from "@/types/campground";
import { createPublicSupabaseClient } from "@/lib/supabase/client";
import type { CampgroundDirectoryFacets, CampgroundDirectoryQuery, CampgroundDirectoryResult } from "@/lib/campgrounds/directory-query";

const FALLBACK_IMAGE = "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1400&q=80";
type DbCampground = { id:string; slug:string; name:string; short_description:string|null; address:string; district:string|null; latitude:number|string; longitude:number|string; elevation_m:number|null; verification_status:"unverified"|"community_updated"|"verified"|"needs_update"; last_verified_at:string|null; featured:boolean; provinces:{name:string}|{name:string}[]|null; regencies:{name:string}|{name:string}[]|null; campground_type_relations:{campground_types:{name:string}|{name:string}[]|null}[]|null; campground_facilities:{is_available:boolean;facilities:{name:string}|{name:string}[]|null}[]|null; campground_access:{vehicle_type:string;is_accessible:boolean}[]|null; campground_suitable_for:{label:string}[]|null; campground_prices:{amount_idr:number|string;unit:string|null;sort_order:number}[]|null; campground_photos:{storage_path:string;is_cover:boolean;sort_order:number}[]|null };
type DbCampgroundDetail = Omit<DbCampground,"campground_facilities"|"campground_access"|"campground_prices"|"campground_photos"> & { description:string|null; capacity_people:number|null; access_description:string|null; check_in_info:string|null; good_to_know:string|null; campground_facilities:{is_available:boolean;note:string|null;facilities:{name:string}|{name:string}[]|null}[]|null; campground_access:{vehicle_type:string;is_accessible:boolean;note:string|null}[]|null; campground_prices:{id:string;type:any;label:string;amount_idr:number|string;unit:string|null;note:string|null;sort_order:number}[]|null; campground_contacts:{id:string;type:any;label:string|null;value:string;is_primary:boolean}[]|null; campground_photos:{id:string;storage_path:string;alt_text:string|null;caption:string|null;credit_name:string|null;source_url:string|null;is_cover:boolean;sort_order:number}[]|null };
const DIRECTORY_SELECT=`id,slug,name,short_description,address,district,latitude,longitude,elevation_m,verification_status,last_verified_at,featured,provinces(name),regencies(name),campground_type_relations(campground_types(name)),campground_facilities(is_available,facilities(name)),campground_access(vehicle_type,is_accessible),campground_suitable_for(label),campground_prices(amount_idr,unit,sort_order),campground_photos(storage_path,is_cover,sort_order)`;
const DETAIL_SELECT=`id,slug,name,short_description,description,address,district,latitude,longitude,elevation_m,capacity_people,access_description,check_in_info,good_to_know,verification_status,last_verified_at,featured,provinces(name),regencies(name),campground_type_relations(campground_types(name)),campground_facilities(is_available,note,facilities(name)),campground_access(vehicle_type,is_accessible,note),campground_suitable_for(label),campground_prices(id,type,label,amount_idr,unit,note,sort_order),campground_contacts(id,type,label,value,is_primary),campground_photos(id,storage_path,alt_text,caption,credit_name,source_url,is_cover,sort_order)`;
function one<T>(value:T|T[]|null):T|null{return Array.isArray(value)?value[0]??null:value}
function photoUrl(path:string){return createPublicSupabaseClient().storage.from("campground-photos").getPublicUrl(path).data.publicUrl}
function publicVerification(status:DbCampground["verification_status"]):VerificationStatus{return status==="unverified"?"needs_update":status}
function mapCampground(row:DbCampground):Campground{const prices=[...(row.campground_prices??[])].sort((a,b)=>Number(a.amount_idr)-Number(b.amount_idr)||a.sort_order-b.sort_order);const price=prices[0];const photos=[...(row.campground_photos??[])].sort((a,b)=>Number(b.is_cover)-Number(a.is_cover)||a.sort_order-b.sort_order);const photo=photos[0];return{id:row.id,slug:row.slug,name:row.name,shortDescription:row.short_description??"Informasi campground sedang dilengkapi oleh IndoCampingLovers.",province:one(row.provinces)?.name??"Indonesia",regency:one(row.regencies)?.name??"",district:row.district??undefined,address:row.address,latitude:Number(row.latitude),longitude:Number(row.longitude),elevationM:row.elevation_m??undefined,types:(row.campground_type_relations??[]).map(x=>one(x.campground_types)?.name).filter((x):x is string=>Boolean(x)),priceFrom:price?Number(price.amount_idr):0,priceUnit:price?.unit??"kunjungan",facilities:(row.campground_facilities??[]).filter(x=>x.is_available).map(x=>one(x.facilities)?.name).filter((x):x is string=>Boolean(x)),access:(row.campground_access??[]).filter(x=>x.is_accessible).map(x=>x.vehicle_type),suitableFor:(row.campground_suitable_for??[]).map(x=>x.label),image:photo?photoUrl(photo.storage_path):FALLBACK_IMAGE,verificationStatus:publicVerification(row.verification_status),lastVerifiedAt:(row.last_verified_at??new Date(0).toISOString()).slice(0,10),featured:row.featured}}
function mapCampgroundDetail(row:DbCampgroundDetail):CampgroundDetail{const base=mapCampground(row as DbCampground);const prices=[...(row.campground_prices??[])].sort((a,b)=>a.sort_order-b.sort_order||Number(a.amount_idr)-Number(b.amount_idr)).map(x=>({id:x.id,type:x.type,label:x.label,amountIdr:Number(x.amount_idr),unit:x.unit??undefined,note:x.note??undefined,sortOrder:x.sort_order}));const photos=[...(row.campground_photos??[])].sort((a,b)=>Number(b.is_cover)-Number(a.is_cover)||a.sort_order-b.sort_order).map(x=>({id:x.id,url:photoUrl(x.storage_path),altText:x.alt_text??undefined,caption:x.caption??undefined,creditName:x.credit_name??undefined,sourceUrl:x.source_url??undefined,isCover:x.is_cover,sortOrder:x.sort_order}));return{...base,image:photos[0]?.url??base.image,description:row.description??undefined,capacityPeople:row.capacity_people??undefined,accessDescription:row.access_description??undefined,checkInInfo:row.check_in_info??undefined,goodToKnow:row.good_to_know??undefined,prices,contacts:(row.campground_contacts??[]).sort((a,b)=>Number(b.is_primary)-Number(a.is_primary)).map(x=>({id:x.id,type:x.type,label:x.label??undefined,value:x.value,isPrimary:x.is_primary})),photos,facilityDetails:(row.campground_facilities??[]).filter(x=>x.is_available).map(x=>({name:one(x.facilities)?.name??"Fasilitas",note:x.note??undefined})),accessDetails:(row.campground_access??[]).filter(x=>x.is_accessible).map(x=>({vehicleType:x.vehicle_type,note:x.note??undefined})),verification:{status:publicVerification(row.verification_status),verifiedAt:row.last_verified_at??undefined}}}

type SearchMatch={campground_id:string;total_count:number|string};
async function searchDirectory(supabase:ReturnType<typeof createPublicSupabaseClient>,query:CampgroundDirectoryQuery,page:number,pageSize=query.pageSize){return supabase.rpc("search_campgrounds",{p_q:query.q??null,p_province:query.province??null,p_regency:query.regency??null,p_types:query.types,p_facilities:query.facilities,p_access:query.access,p_min_price:query.minPrice??null,p_max_price:query.maxPrice??null,p_sort:query.sort,p_limit:pageSize,p_offset:(page-1)*pageSize});}
async function loadCampgroundsByIds(supabase:ReturnType<typeof createPublicSupabaseClient>,ids:string[]){if(!ids.length)return[];const{data,error}=await supabase.from("campgrounds").select(DIRECTORY_SELECT).in("id",ids);if(error)throw new Error(`Unable to load campground directory: ${error.message}`);const byId=new Map(((data??[])as unknown as DbCampground[]).map(row=>[row.id,mapCampground(row)]));return ids.map(id=>byId.get(id)).filter((x):x is Campground=>Boolean(x));}

export async function getCampgroundDirectory(query:CampgroundDirectoryQuery):Promise<CampgroundDirectoryResult<Campground>>{const supabase=createPublicSupabaseClient();let page=query.page;let{data:matches,error:matchError}=await searchDirectory(supabase,query,page);if(matchError)throw new Error(`Unable to search campground directory: ${matchError.message}`);let rows=(matches??[])as SearchMatch[];if(!rows.length&&page>1){const{data:firstMatches,error:firstError}=await searchDirectory(supabase,query,1);if(firstError)throw new Error(`Unable to search campground directory: ${firstError.message}`);const firstRows=(firstMatches??[])as SearchMatch[];const total=firstRows.length?Number(firstRows[0].total_count):0;const totalPages=Math.max(1,Math.ceil(total/query.pageSize));if(total===0)return{items:[],total:0,page:1,pageSize:query.pageSize,totalPages:1};page=Math.min(page,totalPages);if(page===1)rows=firstRows;else{const{data:lastMatches,error:lastError}=await searchDirectory(supabase,query,page);if(lastError)throw new Error(`Unable to search campground directory: ${lastError.message}`);rows=(lastMatches??[])as SearchMatch[];}}const total=rows.length?Number(rows[0].total_count):0;const totalPages=Math.max(1,Math.ceil(total/query.pageSize));if(!rows.length)return{items:[],total,page:1,pageSize:query.pageSize,totalPages:1};const ids=rows.map(x=>x.campground_id);const items=await loadCampgroundsByIds(supabase,ids);return{items,total,page,pageSize:query.pageSize,totalPages};}
export const DIRECTORY_MAP_RESULT_LIMIT=500;
export type CampgroundMapResult={items:Campground[];total:number;mappableTotal:number;truncated:boolean};
export async function getCampgroundMapResults(query:CampgroundDirectoryQuery):Promise<CampgroundMapResult>{const supabase=createPublicSupabaseClient();const{data,error}=await searchDirectory(supabase,query,1,DIRECTORY_MAP_RESULT_LIMIT);if(error)throw new Error(`Unable to search campground map: ${error.message}`);const rows=(data??[])as SearchMatch[];const total=rows.length?Number(rows[0].total_count):0;const items=(await loadCampgroundsByIds(supabase,rows.map(x=>x.campground_id))).filter(item=>Number.isFinite(item.latitude)&&Number.isFinite(item.longitude)&&item.latitude>=-90&&item.latitude<=90&&item.longitude>=-180&&item.longitude<=180);return{items,total,mappableTotal:items.length,truncated:total>DIRECTORY_MAP_RESULT_LIMIT};}
export async function getCampgroundDirectoryFacets():Promise<CampgroundDirectoryFacets>{const supabase=createPublicSupabaseClient();const[provinces,regencies,types,facilities,access]=await Promise.all([supabase.from("provinces").select("name,slug").order("name"),supabase.from("regencies").select("name,slug,provinces(slug)").order("name"),supabase.from("campground_types").select("name,slug").order("name"),supabase.from("facilities").select("name,slug").order("sort_order").order("name"),supabase.from("campground_access").select("vehicle_type").eq("is_accessible",true)]);const error=provinces.error??regencies.error??types.error??facilities.error??access.error;if(error)throw new Error(`Unable to load directory facets: ${error.message}`);return{provinces:(provinces.data??[]).map(x=>({value:x.slug,label:x.name})),regencies:(regencies.data??[]).map((x:any)=>({value:x.slug,label:x.name,province:one(x.provinces)?.slug??""})),types:(types.data??[]).map(x=>({value:x.slug,label:x.name})),facilities:(facilities.data??[]).map(x=>({value:x.slug,label:x.name})),access:[...new Set((access.data??[]).map(x=>x.vehicle_type))].sort().map(value=>({value,label:value}))}}
export async function getPublishedCampgrounds():Promise<Campground[]>{const result=await getCampgroundDirectory({types:[],facilities:[],access:[],sort:"recommended",view:"list",page:1,pageSize:100});return result.items}
export async function getFeaturedCampgrounds(limit=3):Promise<Campground[]>{const supabase=createPublicSupabaseClient();const{data,error}=await supabase.from("campgrounds").select(DIRECTORY_SELECT).eq("featured",true).order("name").limit(limit);if(error)throw new Error(`Unable to load featured campgrounds: ${error.message}`);return((data??[])as unknown as DbCampground[]).map(mapCampground)}
export async function getCampgroundBySlug(slug:string):Promise<CampgroundDetail|null>{const supabase=createPublicSupabaseClient();const{data,error}=await supabase.from("campgrounds").select(DETAIL_SELECT).eq("slug",slug).maybeSingle();if(error)throw new Error(`Unable to load campground: ${error.message}`);return data?mapCampgroundDetail(data as unknown as DbCampgroundDetail):null}
export async function getRelatedCampgrounds(campground:Campground,limit=3):Promise<Campground[]>{const all=await getPublishedCampgrounds();return all.filter(x=>x.slug!==campground.slug&&(x.province===campground.province||x.types.some(t=>campground.types.includes(t)))).slice(0,limit)}
